;Aperture_NDFilter_ColorFilter_LightSource/RX  (folder Structure)
;FFCMethod=Synthetic/Normal

[Movement]
; Sphere_Mapping=-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6
; Cylinder_Mapping=-4,-3.75,-3.5,-3.25,-3,-2.75,-2.5,-2.25,-2,-1.75,-1.5,-1.25,-1,-0.75,-0.5,-0.25,0
; Axis_Mapping=0,15,30,45,60,75,90,105,120,135,150,165

[Dark]
Folder_Rule=
Suffix=Dark.tif
Path=

[DarkList]
Folder_Rule=
Suffix=
Path=

[ColorShift]
Folder_Rule=Aperture_NDFilter_ColorFilter
Suffix=ColorShift.json
Path=

[FFC]
Suffix=ffc.tif
Folder_Rule=Aperture_ColorFilter/RX
Path=
FFC_Method=Synthetic
; RX: FFC_Method=Synthetic
Sphere_Mapping=-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6
Cylinder_Mapping=-4,-3.75,-3.5,-3.25,-3,-2.75,-2.5,-2.25,-2,-1.75,-1.5,-1.25,-1,-0.75,-0.5,-0.25,0
Axis_Mapping=0,15,30,45,60,75,90,105,120,135,150,165

[Distortion]
Folder_Rule=
Suffix=Distortion.json
Path=

[Offset]
Folder_Rule=
Suffix=Offset.json
Path=

[FourColor]
Folder_Rule = Aperture_NDFilter
Suffix=RMatrix.json
Path=
Sphere_Mapping=-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6
Cylinder_Mapping=-4,-3.75,-3.5,-3.25,-3,-2.75,-2.5,-2.25,-2,-1.75,-1.5,-1.25,-1,-0.75,-0.5,-0.25,0
Axis_Mapping=0,15,30,45,60,75,90,105,120,135,150,165
Sphere_Lum_Coefficient=0.949, 0.955, 0.961, 0.967, 0.973, 0.979, 0.986, 0.993, 1.000, 1.007, 1.015, 1.023, 1.031, 1.040, 1.049
Cylinder_Lum_Coefficient=0.956, 0.967, 0.967, 0.968, 0.981, 0.982, 0.984, 0.989, 0.990, 0.992, 0.989, 0.989, 0.991, 0.994, 0.994, 0.997, 1.000

[Luminance]
Folder_Rule=
Suffix=Luminance.json
Path=

[Radiance]
Folder_Rule=
Suffix=Radiance.json
Path=

[FourColorCalibration]
Folder_Rule =Aperture_NDFilter/ColorFilter_LightSource
Suffix=M.tif
Path=

[FOVCrop]
Folder_Rule=
Suffix=FOVCrop.json
Path=

[Flip_Rotate]
Folder_Rule=
Suffix=Flip_Rotate.json
Path=

